# -*- coding: utf-8 -*-
"""hw5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AIaNvpK7PWI8tHOKzVtsWwCgw_44kwbx
"""

import requests as rq
import bs4
import pandas as pd
import plotly.express as px

url = 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)'
page = rq.get(url)
page.text[0 : 214]
bs4page = bs4.BeautifulSoup(page.text, 'html.parser')
tables = bs4page.find_all('table',{'class':"wikitable"})

from io import StringIO
GDP = pd.read_html(StringIO(str(tables[0])))[0]

GDP.dropna(inplace=True)
GDP.head()

GDP = GDP.iloc[:, [0, 1]]
GDP.columns = ['Country', 'GDP (US$ Million)']

fig = px.bar(GDP.head(50), x='Country', y='GDP (US$ Million)',
             title='Top 20 Countries by GDP (US$ Million)',
             labels={'GDP (US$ Million)': 'GDP in US$ Million'},
             color='Country')
fig.show()